export const ORDER_CAKE = "ORDER_CAKE";
export const RESTOCK_CAKE = "RESTOCK_CAKE";
export const ORDER_ICECREAM = "ORDER_ICECREAM";
export const RESTOCK_ICECREAM = "RESTOCK_ICECREAM";
export const FETCH_REQUEST_USERS = "FETCH_REQUEST_USERS";
export const FETCH_REQUEST_SUCCEEDED = "FETCH_REQUEST_SUCCEEDED";
export const FETCH_REQUEST_FAILED = "FETCH_REQUEST_FAILED";
